#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unzipper
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ZipFiles")]
	public partial class UnzipDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertZipFileName(ZipFileName instance);
    partial void UpdateZipFileName(ZipFileName instance);
    partial void DeleteZipFileName(ZipFileName instance);
    #endregion
		
		public UnzipDataDataContext() : 
				base(global::Unzipper.Properties.Settings.Default.ZipFilesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UnzipDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UnzipDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UnzipDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UnzipDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ZipFileName> ZipFileNames
		{
			get
			{
				return this.GetTable<ZipFileName>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZipFileName")]
	public partial class ZipFileName : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ZipFileName1;
		
		private bool _Extracted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnZipFileName1Changing(string value);
    partial void OnZipFileName1Changed();
    partial void OnExtractedChanging(bool value);
    partial void OnExtractedChanged();
    #endregion
		
		public ZipFileName()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ZipFileName", Storage="_ZipFileName1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ZipFileName1
		{
			get
			{
				return this._ZipFileName1;
			}
			set
			{
				if ((this._ZipFileName1 != value))
				{
					this.OnZipFileName1Changing(value);
					this.SendPropertyChanging();
					this._ZipFileName1 = value;
					this.SendPropertyChanged("ZipFileName1");
					this.OnZipFileName1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extracted", DbType="Bit NOT NULL")]
		public bool Extracted
		{
			get
			{
				return this._Extracted;
			}
			set
			{
				if ((this._Extracted != value))
				{
					this.OnExtractedChanging(value);
					this.SendPropertyChanging();
					this._Extracted = value;
					this.SendPropertyChanged("Extracted");
					this.OnExtractedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
